### ISSUE TITLE
Security Concerns for Access Tokens on a Mobile Device

### ISSUE THREAD

**Issue by mootrichard** [mtwichel/square-connect-flutter-library#34]
I wanted to reach out regarding security concerns that you need to account for with storing `access_token` on an untrusted device.

https://developer.okta.com/blog/2019/01/22/oauth-api-keys-arent-safe-in-mobile-apps

It's possible to extract access tokens from mobile applications from string searching the code or simply doing a MITM attack and decrypting the HTTPS requests to look at the access token in the headers.

This is the same reason you wouldn't want to deploying access tokens onto a web front-end, since no matter how much you try, the deployment target is an untrusted environment.

**Comment by mtwichel** [comment]
Thanks for the insight and info. I've adjusted the package to not support that flow any longer.
